"""autogenerated by genmsg_py from Navdata.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg

class Navdata(roslib.message.Message):
  _md5sum = "49de2abc292ef1d9be7a19689625ceb8"
  _type = "ar_drone2/Navdata"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Twist position
float32 altitude 
uint32 battery
        

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into it's linear and angular parts. 
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['position','altitude','battery']
  _slot_types = ['geometry_msgs/Twist','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       position,altitude,battery
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Navdata, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Twist()
      if self.altitude is None:
        self.altitude = 0.
      if self.battery is None:
        self.battery = 0
    else:
      self.position = geometry_msgs.msg.Twist()
      self.altitude = 0.
      self.battery = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6dfI.pack(_x.position.linear.x, _x.position.linear.y, _x.position.linear.z, _x.position.angular.x, _x.position.angular.y, _x.position.angular.z, _x.altitude, _x.battery))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.position.linear.x, _x.position.linear.y, _x.position.linear.z, _x.position.angular.x, _x.position.angular.y, _x.position.angular.z, _x.altitude, _x.battery,) = _struct_6dfI.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6dfI.pack(_x.position.linear.x, _x.position.linear.y, _x.position.linear.z, _x.position.angular.x, _x.position.angular.y, _x.position.angular.z, _x.altitude, _x.battery))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.position.linear.x, _x.position.linear.y, _x.position.linear.z, _x.position.angular.x, _x.position.angular.y, _x.position.angular.z, _x.altitude, _x.battery,) = _struct_6dfI.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6dfI = struct.Struct("<6dfI")
